### ISSUE TITLE
Ball shading a cone

### ISSUE THREAD

**Issue by minhthien2016** [marmotghost/tikz-3dtools#9]
I see [this question](https://tex.stackexchange.com/questions/626186/how-do-i-shade-a-cone-to-match-ball-shading). From now, there is no answer to this question. I copy this code from your manual, but I think, I do not get ball shading. 
```
\documentclass[tikz,border=3mm]{standalone}
\usepackage{tikz-3dplot}
\usetikzlibrary{3dtools}% https://github.com/marmotghost/tikz-3dtools
\begin{document}
\begin{tikzpicture}[3d/install view=%
	{phi=110,psi=0,theta=60}]
	\pic{3d/shaded cone={r=2,h=3}};
\end{tikzpicture}
\end{document}
```
![image](https://user-images.githubusercontent.com/55286040/150908414-eedbec62-bfe6-4d33-9e3e-6d72facc952e.png)

**Comment by marmotghost** [comment]
These shadings are, unfortunately, things that do not necessarily work across all the viewers. I do, however, reproduce the above screen shot, which I believe to be the expected outcome, with Preview and Acrobat Reader on a Mac. It can very well be that this does not work with other viewers, and if this is the root of the problem here then there is probably not much that can be done without really delving into how pgf talks to the viewers.

**Comment by minhthien2016** [comment]
Thank you very much.

**Comment by marmotghost** [comment]
Shading has viewer-dependent issues, and I do not have the skills to fix this
